
name: front_pants
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.0.9  
  youtube_player_flutter: ^8.1.0
  flutter_secure_storage: ^9.2.2
  google_generative_ai: ^0.4.6
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/home.png
    - assets/plant.png
    - assets/ai.png
    - assets/profile.png